#!/bin/bash
###################################
## RICE DATA (continuous)
###################################

## set resources
plink=plink  # directory with plink binary
#plink=plink  # directory with plink binary
trait=PH

cd data

## retrieve group information
## create new phenotypes file and ids file for Plink subsetting
## Run R script "prep_rice_data.R" from terminal and submit the arguments "plantgrainPhenotypes.txt", "rice_group.reference" and "PH" to the script 
Rscript ../software/prep_rice_data_pipeline.R plantgrainPhenotypes.txt ../software/rice_group.reference $trait


## this is to match ids between files
sed -i 's/\_//g' GBSnew.ped 
sed -i 's/a//g' GBSnew.ped

## use Plink to subset data
$plink --file GBSnew --keep ids --chr 1,2,6,7 --recode --out rice

rm rice.log rice.nosex  # remove log-file generated by plink
