#!/bin/bash
###################################
## RICE DATA (continuous)
###################################

## set resources
plink=plink  # directory with plink binary


cd ../data

## retrieve group information
## create new phenotypes file and ids file for Plink subsetting
## Run R script "prep_rice_data.R" from terminal and submit the arguments "plantgrainPhenotypes.txt", "rice_group.reference" and "PH" to the script 
Rscript ../1.preparatory_steps/prep_rice_data.R plantgrainPhenotypes.txt ../1.preparatory_steps/rice_group.reference PH

wc -l rice_phenotypes.txt
wc -l ids


## this is to match ids between files
sed -i 's/\_//g' GBSnew.ped 
sed -i 's/a//g' GBSnew.ped

## use Plink to subset data
$plink --file GBSnew --keep ids --chr 1,2,6,7 --recode --out rice

rm rice.log rice.nosex  # remove log-file generated by plink

###################################
## DOG DATA (binary)
###################################

## prep phenotypes
Rscript --vanilla ../1.preparatory_steps/prep_dogpheno.R UCD_2014.tfam

## subset genotypes
$plink --dog --tfile UCD_2014 --chr 25,26,27,28,29 --recode --out dogs

echo "DONE!"
