#!/bin/bash
###################################
## PIG DATA (binary)
###################################

## set resources
# plink=plink
plink=/home/filippo/Downloads/plink  # directory with plink binary

## Download data (rice, continuous)
echo "Downloading pigs data ..."

### Check for dir, if not found create it using the mkdir ##
[ ! -d "data" ] && mkdir -p "data"  # mkdir = make directory called data in relative path ".."

cd data
  
wget http://www.jackdellequerce.com/data/GWAS_cohort.tar.gz  # wget - retrieve content from web servers

tar -xvzf GWAS_cohort.tar.gz  # extract files from archive

wc -l GWAS_cohort.fam # wc = word count, -l = count lines: Number of genotypes in ped file
$plink --bfile GWAS_cohort --freq --out freq
wc -l freq.frq  # Number of markers in map file

wc -l pheno # Number of phenotypic records

## use Plink to subset data
$plink --bfile GWAS_cohort --chr 9,10,11,12,13,14,15 --recode --out pigs
rm pigs.log pigs.nosex  # remove log-file generated by plink

$plink --file pigs --missing --out pigs
avg_miss_rate=`awk '{ total += $6; count++ } END { print total/count }' pigs.imiss`

## preprocess phenotypic data
awk '{print $1, $2, $3-1}' pheno > temp
echo -e "fam id phenotype" | cat - temp | awk '{print $2,$1,$3}' > pigs_phenotypes.txt

## clean repo
rm pigs.imiss pigs.lmiss pigs.log pigs.nosex 
rm GWAS_cohort.tar.gz
rm freq*
rm GWAS_cohort.*
#rm pheno temp

echo "Average missing rate is ${avg_miss_rate}"
echo "DONE!"
